
target:YFPageViewControllerVC  do

platform :ios, '8.0'
pod 'Masonry'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage' ,’~> 4.2.0'
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'NJKWebViewProgress'
pod 'UMengAnalytics-NO-IDFA'
pod 'IQKeyboardManager'
pod 'libqrencode'
pod 'mp3lame-for-ios'
pod 'iOS-AlipaySDK'
pod 'JRDB'
pod 'Reachability'
pod 'JPush'
pod 'UMengUShare' ,’~> 6.0.3'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'ReactiveObjC'
end
